#!/bin/bash
set -e

# command taken from https://github.com/JLLeitschuh/ktlint-gradle  task addKtlintFormatGitPreCommitHook
filesToFormat="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.java|\.kt/ { print $NF}')"

echo "Files to format $filesToFormat"
for sourceFilePath in $filesToFormat
do
  google-java-format -r "$(pwd)/$sourceFilePath"
  git add $sourceFilePath
done;
